[nfs]
172.31.88.220 ansible_ssh_user='ec2-user'

[webservers]
172.31.17.142 ansible_ssh_user='ec2-user'
172.31.23.124 ansible_ssh_user='ec2-user'

[db]
172.31.90.194 ansible_ssh_user='ubuntu' 

# [lb]
# 172.31.27.223 ansible_ssh_user='ubuntu'