# ---
# - hosts: all
# - import_playbook: ../static-assignments/common.yml

# - hosts: uat-webservers
# - import_playbook: ../static-assignments/uat-webservers.yml

---

- name: Include dynamic variables 
  hosts: all
  tasks:
   - name: kkkk
     import_playbook: ../static-assignments/common.yml 
   - name: ccc  
     include: ../dynamic-assignments/env-vars.yml
  tags:
    - always
- gather_facts: no  

- name: Webserver assignment
  hosts: uat-webservers
  tasks:
  # import_playbook: ../static-assignments/webservers.yml
   - import_playbook: ../static-assignments/uat-webservers.yml
- gather_facts: no
# - name: Loadbalancers assignment
#   hosts: lb
#   import_playbook: ../static-assignments/loadbalancers.yml
#   when: load_balancer_is_required 

